#!/usr/bin/env python3
import sys
import pathlib


source_file = pathlib.Path(sys.argv[1])
dest_file = pathlib.Path(sys.argv[2])
sources = sys.argv[3:]

contents = source_file.read_text()
for source in sources:
    path = pathlib.Path(source).absolute()
    if path.suffix == ".vhd":
        type_ = "VHDL_FILE"
    elif path.suffix == ".qip":
        type_ = "QIP_FILE"
    elif path.suffix == ".sdc":
        type_ = "SDC_FILE"
    else:
        print(f"Ignoring file {path}")
        continue
    contents += f"set_global_assignment -name {type_} {path}\n"

dest_file.write_text(contents)
